name: Fetch World Archery Data

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 7 * * 0' # Runs weekly on Sunday at 7:00 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch event data and save as JSON
        run: python fetch_events.py

      - name: Commit and push data file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add world_archery_data.json
          
          if ! git diff --staged --quiet -- world_archery_data.json; then
            echo "Changes detected in data file. Committing..."
            TIMESTAMP=$(date -u +'%Y-%m-%d %H:%M:%S %Z')
            git commit -m "Update World Archery data [$TIMESTAMP]"
            git push
          else
            echo "No changes detected in data file."
          fi
